# KallistiOS ##version##
#
# arch/dreamcast/util/Makefile
# Copyright (C) 2001 Megan Potter
#

OBJS = vmu_fb.o vmu_pkg.o vmu_printf.o screenshot.o minifont.o fb_console.o
SUBDIRS =

include $(KOS_BASE)/Makefile.prefab
