# KallistiOS ##version##
#
# kernel/libc/atomics/Makefile
# Copyright (C) 2025 Falco Girgis
#

TARGET = libatomic.a
SUBDIRS =
KOS_CFLAGS += -fno-lto

OBJS = atomics.o

include $(KOS_BASE)/addons/Makefile.prefab
